# -*- makefile -*-
#
#  Common definitions for all systems that use GNU make
#


# Tack the extra deps onto the autogenerated variables
INCFLAGS += -I"$(LIBSUBDOMAINZ_BUILD_DIR)"/include
LOCAL_LIBS += $(LIBSUBDOMAINZ)
BUILD_DIR = $(shell pwd)
LIBSUBDOMAINZ_CFLAGS = $(SUBDOMAINZ_MMAP_EXEC)
LIBSUBDOMAINZ_BUILD_DIR = $(BUILD_DIR)/libsubdomainz-$(arch)

ifeq ($(srcdir),.)
  LIBSUBDOMAINZ_SRC_DIR := $(shell pwd)/libsubdomainz
else ifeq ($(srcdir),..)
  LIBSUBDOMAINZ_SRC_DIR := $(shell pwd)/../libsubdomainz
else
  LIBSUBDOMAINZ_SRC_DIR := $(realpath $(srcdir)/libsubdomainz)
endif

LIBSUBDOMAINZ_CONFIGURE = "$(LIBSUBDOMAINZ_SRC_DIR)"/configure --disable-static \
	--with-pic=yes --disable-dependency-tracking

#
# libsubdomainz.mk or libsubdomainz.darwin.mk contains rules for building the actual library
#
